apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    name: nodeport-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32143
  selector:
    app: hello